version: '3'
services:
  test_case_daemon:
    container_name: test_case_daemon
    image: tiangolo/uwsgi-nginx-flask:python3.7
    restart: always
    ports:
      - 8090:80
    volumes:
      - ./src/test_case_daemon.py:/app/main.py
      - ./src/config.py:/app/config.py
      - ./test_case:/test_case:rw

  judger:
    container_name: judger
    image: judger
    read_only: true
    restart: always
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./test_case:/test_case:ro
      - ./log:/log
      - ./run:/run
    ports:
      - 9191:9191
    
