version: '3'
services:
  judger:
    container_name: judger
    build: .
    read_only: true
    restart: always
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - /test_case:/test_case:ro
      - /log:/log
    ports:
      - 9191:9191
    